---
image: "robertdebock/github-action-molecule:5.0.2"

variables:
  PY_COLORS: 1

molecule:
  script:
    - if [ -f tox.ini ] ; then tox ; fi
    - if [ ! -f tox.ini ] ; then molecule test ; fi
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  parallel:
    matrix:
      - image: "centos"
        tag: "7"
      - image: "centos"
        tag: "8"
      - image: "centos"
        tag: "latest"
      - image: "amazonlinux"
        tag: "2"
      - image: "ubuntu"
        tag: "latest"
      - image: "ubuntu"
        tag: "focal"
      - image: "ubuntu"
        tag: "bionic"
      - image: "debian"
        tag: "latest"
      - image: "debian"
        tag: "bookworm"

# galaxy:
#   script:
#     - ansible-galaxy role import --api-key ${GALAXY_API_KEY} mullholland ${CI_PROJECT_NAME}
#   rules:
#     - if: $CI_COMMIT_TAG != null
