---
- name: setup-Debian | Add nginx nginx signing key
  ansible.builtin.apt_key:
    url: "{{ nginx_signing_key }}"
    state: present

- name: setup-Debian | Enable nginx repository
  ansible.builtin.template:
    src: "repositories/Debian.j2"
    dest: "/etc/apt/sources.list.d/nginx.list"
    owner: root
    group: root
    mode: "0644"
  register: nginx_repository_update

- name: setup-Debian | Ensure nginx is installed
  ansible.builtin.apt:
    name: "{{ nginx_package_name }}"
    state: present
    update_cache: "{{ 'true' if nginx_repository_update.changed else 'false' }}"
