---
molecule_exceptions:
  - variation: centos-stream9
    reason: "No supported Repository ATM"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
