---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: "${scenario:-default}-${ansible:-current}-${platform:-ubuntu2004}"
    image: "${namespace:-ghcr.io/mullholland}/docker-molecule-${platform:-ubuntu2004}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ASYNC_DIR: /tmp/.ansible_async
    ANSIBLE_REMOTE_TMP: /tmp/.ansible
verifier:
  name: ansible
