---
# Ansible managed

name: Release to Ansible Galaxy

on:
  release:
    types: [released]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
