---
#
# Ansible managed
#

name: Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '27 14 14 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "8"
          - image: "centos"
            tag: "latest"
          - image: "amazonlinux"
            tag: "2"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "focal"
          - image: "ubuntu"
            tag: "bionic"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "bullseye"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      # - name: disable apparmor for mysql
      #   run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      # - name: parse apparmor for mysql
      #   run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          namespace: mullholland
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
