---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '27 14 14 * *'

# If a 403 error occurs, make sure to set content permission to write
# see: https://github.com/go-semantic-release/action/issues/27
permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "centos"
            tag: "7"
          - image: "centos"
            tag: "8"
          - image: "centos"
            tag: "latest"
          - image: "amazonlinux"
            tag: "2"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "focal"
          - image: "ubuntu"
            tag: "bionic"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "bookworm"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@6.0.0
        with:
          namespace: mullholland
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
